# ==========================================================
# Apache Flume
# Source: exec (tail -F)
# Channel: memory
# Sink: HDFS
# ==========================================================

a1.sources = r1
a1.channels = c1
a1.sinks = k1

# ---------------- SOURCE ----------------
a1.sources.r1.type = exec
a1.sources.r1.command = tail -F /opt/project/data/input/events.log
a1.sources.r1.shell = /bin/bash -c
a1.sources.r1.channels = c1

# ---------------- CHANNEL ----------------
a1.channels.c1.type = memory
a1.channels.c1.capacity = 10000
a1.channels.c1.transactionCapacity = 1000

# ---------------- HDFS SINK ----------------
a1.sinks.k1.type = hdfs
a1.sinks.k1.channel = c1

a1.sinks.k1.hdfs.path = hdfs://namenode:9000/bigdata/ecommerce/raw/%Y/%m/%d/%H
a1.sinks.k1.hdfs.filePrefix = events-
a1.sinks.k1.hdfs.fileSuffix = .jsonl

a1.sinks.k1.hdfs.useLocalTimeStamp = true

a1.sinks.k1.hdfs.fileType = DataStream
a1.sinks.k1.hdfs.writeFormat = Text

# Roll rápido para facilitar a demonstração
a1.sinks.k1.hdfs.rollInterval = 10
a1.sinks.k1.hdfs.rollSize = 0
a1.sinks.k1.hdfs.rollCount = 0

# Cluster acadêmico com apenas um DataNode
a1.sinks.k1.hdfs.minBlockReplicas = 1