a1.sources = r1
a1.channels = c1
a1.sinks = k1

# SOURCE
# -n 0 evita reenviar o conteúdo antigo quando o Flume reinicia.
a1.sources.r1.type = exec
a1.sources.r1.command = tail -n 0 -F /data/events.log
a1.sources.r1.shell = /bin/bash -c
a1.sources.r1.channels = c1

# CHANNEL
a1.channels.c1.type = memory
a1.channels.c1.capacity = 10000
a1.channels.c1.transactionCapacity = 1000

# HDFS SINK
a1.sinks.k1.type = hdfs
a1.sinks.k1.channel = c1

a1.sinks.k1.hdfs.path = hdfs://namenode:9000/bigdata/ecommerce/raw/%Y/%m/%d/%H
a1.sinks.k1.hdfs.filePrefix = events-
a1.sinks.k1.hdfs.fileSuffix = .jsonl
a1.sinks.k1.hdfs.useLocalTimeStamp = true

a1.sinks.k1.hdfs.fileType = DataStream
a1.sinks.k1.hdfs.writeFormat = Text

a1.sinks.k1.hdfs.rollInterval = 10
a1.sinks.k1.hdfs.rollSize = 0
a1.sinks.k1.hdfs.rollCount = 0

a1.sinks.k1.hdfs.minBlockReplicas = 1